### ISSUE TITLE
Minor typo in Examples

### ISSUE THREAD

**Issue by doopz** [NikolaGavric94/laravel-square#23]
Please note that there is a minor typo in the following wiki pages:
  * Examples/Customer Examples.md
  * Examples/Simple Examples.md

The line:
'location_id' => $locationd_id,

should be
'location_id' => $location_id,

**Comment by NikolaGavric94** [comment]
It is fixed, thanks for noticing

**Comment by doopz** [comment]
No problem. Thank you for your library and hard work.
