### ISSUE TITLE
Strong customer authentication (SCA)

### ISSUE THREAD

**Issue by limuel567** [NikolaGavric94/laravel-square#25]
does this package support Strong customer authentication (SCA)
Link: [https://developer.squareup.com/docs/sca-overview](url)

**Comment by NikolaGavric94** [comment]
Not at this time, but a rollout will be deployed as soon as possible to address this change

**Comment by NikolaGavric94** [comment]
I will move this as a feature for later versions since this feature won't be available to everyone (all countries) at start, so might require more time and help to test it properly.
