### ISSUE TITLE
Calling deprecated API: TransactionsApi.charge

### ISSUE THREAD

**Issue by jesseqli** [NikolaGavric94/laravel-square#26]
I'm running into the issue: Calling deprecated API: TransactionsApi.charge

Any ideas on how to fix?

**Comment by NikolaGavric94** [comment]
Hello @jesseqli ,

We are aware of the issue and the fix will be deployed within the next couple of days

**Comment by NikolaGavric94** [comment]
Having some issues with Square and their location locking for certain features which actually blocks me from running tests right now and future development, but working on making it happen, will keep you posted!

**Comment by jessehorne** [comment]
I'm having the same issue.

**Comment by PaulJulio** [comment]
Submitted a PR: https://github.com/NikolaGavric94/laravel-square/pull/27
If you can't wait for approval, you could update your composer.json file to require square/connect version 2.20190710.0

**Comment by NikolaGavric94** [comment]
I will test it out later today (approx. 5-6h from now) and merge the mentioned PR, sorry for the delay

**Comment by NikolaGavric94** [comment]
The new release has been deployed, thanks @PaulJulio for a quick fix, I'm looking into the new version of the library which will work with latest versions of Square API, thanks for being patient
