### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by Reflow1319** [NikolaGavric94/laravel-square#28]
Would it be possible to update the package to support laravel 6

**Comment by NikolaGavric94** [comment]
I will try to push an update for Laravel 6 and make a rollout a new version, will try to do that today

**Comment by NikolaGavric94** [comment]
This is fixed by [v2.3.0](https://github.com/NikolaGavric94/laravel-square/releases/tag/v2.3.0) release 👍
