### ISSUE TITLE
Update an example from 'card_nonce' to 'source_id'

### ISSUE THREAD

**Issue by ya-ya-it** [NikolaGavric94/laravel-square#31]
I updated the plugin to the last version, and it starts to throw an error 'source_id is missing'. As I understand from the code, you changed the 'card_nonce' to 'source_id' field. This code is working for me.

`$options = [
          'amount' => $amount,
          'source_id' => $request->input('nonce'),
          'location_id' => env('SQUARE_LOCATION_ID'),
          'currency' => 'CAD'
];`

Please, change the examples.

**Comment by NikolaGavric94** [comment]
Fixed, thanks
