### ISSUE TITLE
How to add a title to the transaction

### ISSUE THREAD

**Issue by ya-ya-it** [NikolaGavric94/laravel-square#32]
Hello!

Thanks for your package, it's really useful!
I'm building a booking system on Laravel and want to map orders on Square with data in my system.
I'm using a simple code to charge a customer:
```
$options = [
          'amount' => $amount
          'source_id' => $request->input('nonce'),
          'location_id' => env('SQUARE_LOCATION_ID'),
          'currency' => 'CAD'
 ];

$transaction = Square::charge($options);
```

And on the dashboard, all the transactions have the title "Custom Amount".

Is there is a way to change it to some custom message, like in this example?
(https://developer.squareup.com/docs/transactions-api/build-with-transactions)
```
$chargeBody->setReferenceId("Confirmation #12345");
$chargeBody->setNote("This is (not) a helpful note!");
```

I want to have a custom title to be "Order #123" to search on my system as well and map orders and payments.

Thanks!

**Comment by NikolaGavric94** [comment]
Hmm, there isn't a possibility to add the name of the payment yet. I will add the possibility for you to do that and update the library, can't promise any time frames, but I will try to add it in the next few days. :)

**Comment by ya-ya-it** [comment]
Thanks for your reply!
I made a quick fix in my app for that, but I think that might be a useful function to add.
In SquareService inside charge method, I just added
```
$prepData = [
            'idempotency_key' => uniqid(),
            'amount_money'    => [
                'amount'   => $data['amount'],
                'currency' => $currency,
            ],
            'autocomplete' => true,
            'source_id' => $data['source_id'],
            'note' => $data['note'],
];
```
And pass the note with the options. Square use this note to make a title.

**Comment by ya-ya-it** [comment]
Also, I had to add
```
'location_id' => $data['location_id'],
```
to the $prepData, othervise the transaction went to the wrong location.
We have a few locations with the same address connected to one account and without location_id, for some reasons, payments were made under the incorrect location.

**Comment by NikolaGavric94** [comment]
@ya-ya-it it's up and live with [v2.4.1](https://github.com/NikolaGavric94/laravel-square/releases/tag/v2.4.1). Don't forget to read up on the [CHANGELOG.md](https://github.com/NikolaGavric94/laravel-square/blob/v2.4.1/CHANGELOG.md#241---2019-10-23) because this release has some **BREAKING CHANGES**

**Comment by ya-ya-it** [comment]
Thank you for the quick response and fix!
