### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by PlaidFoxSG** [NikolaGavric94/laravel-square#40]
Just curious if this is coming down the immediate pipeline ... ?

**Comment by NikolaGavric94** [comment]
Hello @PlaidFoxSG, yes the plan for the next release is scheduled to be done this weekend (Saturday or Sunday) and from next Monday (23.03) the new release with Laravel 7.4 support will be out.

**Comment by NikolaGavric94** [comment]
The new release will be published today, stay tuned

**Comment by NikolaGavric94** [comment]
Support for Laravel 7 is added in v2.5.0
