### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by dunkin1922** [NikolaGavric94/laravel-square#41]
I'm unable to download and install the package via composer...i get the following when i attempt 

<img width="1362" alt="Screen Shot 2020-03-19 at 8 31 50 AM" src="https://user-images.githubusercontent.com/29736402/77068000-3c9e5900-69bc-11ea-9637-c3c98fe840ea.png">

**Comment by NikolaGavric94** [comment]
Hello @dunkin1922 , the support for Laravel 7 is not yet supported, there will be a release this weekend which adds the support for Laravel 7, keep an eye out for it!

**Comment by NikolaGavric94** [comment]
The new release will be published today, stay tuned

**Comment by dunkin1922** [comment]
thanks mate...looking forward to it !

**Comment by NikolaGavric94** [comment]
Support for Laravel 7 is added in v2.5.0
