### ISSUE TITLE
[HTTP/1.1 401 Unauthorized]

### ISSUE THREAD

**Issue by arunavaghsh84** [NikolaGavric94/laravel-square#45]
![image](https://user-images.githubusercontent.com/25776239/88569466-18ccdd00-d058-11ea-824c-5003e7daa11e.png)

**Comment by NikolaGavric94** [comment]
Hello, could you please post a screenshot of the code from your controller, entire function on ChargeController:39 would be great, thanks!

**Comment by NikolaGavric94** [comment]
I'll be closing this pull request if I don't get a response in the next 2 days. Thanks
