### ISSUE TITLE
How to get user's transactions

### ISSUE THREAD

**Issue by tree1891** [NikolaGavric94/laravel-square#46]
It seems that there is no link with users.

**Comment by NikolaGavric94** [comment]
I think u can find all about it on the wiki page of this project, but here is just one way to get [it](https://github.com/NikolaGavric94/laravel-square/wiki/HasCustomers%20Trait)

**Comment by tree1891** [comment]
It is for customer, customer is not user, I don't use customer, but simple charge

**Comment by NikolaGavric94** [comment]
For simple charges currently there is no way to retrieve all of the user transactions

**Comment by tree1891** [comment]
I have used user_has_square table for relation users and nikolag_transactions.
