### ISSUE TITLE
Can't install on Laravel 8

### ISSUE THREAD

**Issue by jaysonhubt** [NikolaGavric94/laravel-square#48]
When I install this package, I got error:
    - Installation request for laravel/framework (locked at v8.6.0, required as ^8.0) -> satisfiable by laravel/framework[v8.6.0].
    - Installation request for nikolag/laravel-square ^2.5 -> satisfiable by nikolag/laravel-square[2.5.x-dev, v2.5.0].

Installation failed, reverting ./composer.json to its original content.

Thanks for reading!

**Comment by NikolaGavric94** [comment]
Hello,

The library is not compatible for Laravel 8. I've a lot of work right now, but I will do my best to introduce the compatibility with Laravel 8 and optimize it for it by the end of the month.

Thanks for showing interest!

**Comment by jaysonhubt** [comment]
@NikolaGavric94 Thanks for support! Wish you work well!

**Comment by rtconner** [comment]
bump, please? I have to disable square until this is fixed :/

**Comment by NikolaGavric94** [comment]
I haven't forgot about it, Im just unable to do any code changes for at least two weeks, have been having some tech. issues and real life issues

**Comment by Algeneralo** [comment]
@NikolaGavric94 Any updates regarding this issue?
Thanks

**Comment by NikolaGavric94** [comment]
Hello everyone,

I'm glad to report that the update to the library with latest square library version, laravel 7 & 8 version and much more is coming soon, doing some last tests before deploying a working version. Sorry everyone for waiting for so long again.
