### ISSUE TITLE
[HTTP/2 401] UNAUTHORIZED

### ISSUE THREAD

**Issue by sikios182** [NikolaGavric94/laravel-square#49]
![imagen](https://user-images.githubusercontent.com/33912501/99596344-b9565c80-29bb-11eb-8431-ac9adf3ba39e.png)

Here is my controller

![imagen](https://user-images.githubusercontent.com/33912501/99596451-e4d94700-29bb-11eb-834e-8d78456988e1.png)

Hope you can help me,
Thank you.

**Comment by NikolaGavric94** [comment]
The first place I would look if I were you is the `$request->nonce`, looks like that value is not valid

**Comment by sikios182** [comment]
> 
> 
> The first place I would look if I were you is the `$request->nonce`, looks like that value is not valid

My fault, I was using the sandbox setup in mode false, sorry, now it's working.

Thank you!

**Comment by nambp1807** [comment]
![image](https://user-images.githubusercontent.com/49878264/120443299-b13a9900-c3b0-11eb-852d-67865769d1b4.png)

Hope you can help me,
Thank you.

**Comment by nambp1807** [comment]
> @nambp1807 please open up a new issue and also please check that your token you are using is not expired/invalid

My problem when using sandbox is no problem but when I switch to production, I get this error, Please help,
