### ISSUE TITLE
Change table name

### ISSUE THREAD

**Issue by extjac** [NikolaGavric94/laravel-square#53]
How do i change the table names: example... from "nikolag_customers" to "customers". Because when i rename the tables i get the error message.

**Comment by NikolaGavric94** [comment]
Hello, it is not possible to change the table name, why would u want to rename them?

**Comment by extjac** [comment]
Example; after running the migration the table is called "nikolag_customers" and I have table called "customers" instead.

**Comment by NikolaGavric94** [comment]
The library is not hooked to work with custom customers tables, you have any critical issues with this?

**Comment by extjac** [comment]
yep...unfortunately cant use it then. I already have an app working (Models, Controllers, etc)

**Comment by extjac** [comment]
thanks for the answers
