### ISSUE TITLE
[HTTP/2 401] UNAUTHORIZED

### ISSUE THREAD

**Issue by nambp1807** [NikolaGavric94/laravel-square#58]
![image](https://user-images.githubusercontent.com/49878264/120444267-ad5b4680-c3b1-11eb-9eb5-992a2ef1c917.png)

Hope you can help me,
Thank you.

**Comment by NikolaGavric94** [comment]
Have you looked at this: https://github.com/NikolaGavric94/laravel-square/issues/49#issuecomment-731268837?

**Comment by NikolaGavric94** [comment]
Can you post some code where it is happening? @nambp1807

**Comment by nambp1807** [comment]
> Can you post some code where it is happening? @nambp1807

![image](https://user-images.githubusercontent.com/49878264/120575447-4be7b600-c44b-11eb-861b-98128ed9b45c.png)
I am having this problem. Is it because production hasn't activated Square yet?

**Comment by NikolaGavric94** [comment]
Depends, what are you searching for? Maybe posting the picture of your code can help resolve this
