### ISSUE TITLE
SquareConnect\ApiException [HTTP/2 400] {"errors": [{"code": "VALUE_EMPTY","detail": "Field must not be blank","field": "source_id","category": "INVALID_REQUEST_ERROR"}]} 

### ISSUE THREAD

**Issue by sikios182** [NikolaGavric94/laravel-square#59]
![imagen](https://user-images.githubusercontent.com/33912501/128097975-046ebca8-c98b-46f2-a501-9ae2ddfd3200.png)

Here is my controller

![imagen](https://user-images.githubusercontent.com/33912501/128098112-4268dbd3-7115-4f0d-9498-68049e527bb3.png)

Hope you can help me
Regards.

**Comment by NikolaGavric94** [comment]
Hello sikios,

Seems like the `$request->nonce` is blank or empty, did u check you are sending the correct formNonce?

**Comment by sikios182** [comment]
Hi Nikola, that was my bad, I wasn't receiving the nonce in the request,

Thank you for your time.
