### ISSUE TITLE
Request to Upgrade Square Connect to Square PHP SDK

### ISSUE THREAD

**Issue by itsmemanoj** [NikolaGavric94/laravel-square#60]
Hi @NikolaGavric94 ,

Thanks for the great package. It was very useful. And helped me with many projects. But now Square Connect is retired.
Any plan on upgrading to Square PHP SDK?

Thanks

**Comment by NikolaGavric94** [comment]
Hello, thank you for using the library and showing interest, it is really appreciated.

I will upgrade it to use the new sdk, since the time limitation I currently have I would give it around mid to end of October as ETA for this new change.

**Comment by NikolaGavric94** [comment]
Sorry for the long holdup on this. I've made all the necessary code changes for the upgrade, will need to do other admin changes like changelog, readme and some wiki changes first before making a new release. Thanks for being patient

**Comment by NikolaGavric94** [comment]
Done with Github actions setup, now finishing the documentation with the new release and will be releasing a new version by EOD

**Comment by NikolaGavric94** [comment]
New release has been published with ver. [3.0.1](https://github.com/NikolaGavric94/laravel-square/releases/tag/v3.0.1)
