### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by JustCarty** [NikolaGavric94/laravel-square#66]
I just wondered what the timeline is for Laravel 9 support.

Thank you.

**Comment by NeekoGta** [comment]
Yeah, me too, we got this for now :

`nikolag/laravel-square[v3.0.1, ..., 3.0.x-dev] require doctrine/dbal ^3.2 -> found doctrine/dbal[3.2.0, ..., 3.5.x-dev] but these were not loaded, likely because it conflicts with another require.`

Idea?

**Comment by usman735** [comment]
hello
anyone find out the solution

**Comment by NikolaGavric94** [comment]
Sadly due to my IRL obligations I've been unable to work on the library that much. I'm however planning on releasing support for Laravel 9 & 10 as soon as Laravel 10 comes out which would be somewhere between 9th and 15th of February this year.

**Comment by kevinkesslerit** [comment]
> Sadly due to my IRL obligations I've been unable to work on the library that much. I'm however planning on releasing support for Laravel 9 & 10 as soon as Laravel 10 comes out which would be somewhere between 9th and 15th of February this year.

Thank you for your time and code; I'de like to buy you a coffee.
Also: Is there a KANBAN set up for this project by chance?

**Comment by NikolaGavric94** [comment]
@kevinkesslerit Sadly I don't have kanban setup for it, but I rather use notes to write down ideas and other important stuff

**Comment by NikolaGavric94** [comment]
@kevinkesslerit Here is the idea board for 3.1. It's looking pretty slim for now, but will grow over time

**Comment by NikolaGavric94** [comment]
[v3.1.0](https://github.com/NikolaGavric94/laravel-square/releases/tag/v3.1.0) now supports Laravel 9.

Gonna be working on releasing the library compatible with Laravel 10 in the next couple of days.
