### ISSUE TITLE
Wont install on 5.5.x

### ISSUE THREAD

**Issue by zhsolutions** [NikolaGavric94/laravel-square#7]
tried to run the composer require command and it returns telling me it need 5.4.*

nikolag/square v1.0.1 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev,

**Comment by NikolaGavric94** [comment]
Resolved in the newest release [v1.0.2](https://github.com/NikolaGavric94/laravel-square/releases/tag/v1.0.2), please upgrade the dependency.
