### ISSUE TITLE
Bump Square SDK version

### ISSUE THREAD

**Issue by PharaohAsh** [NikolaGavric94/laravel-square#79]
Any chance we can bump to the latest Square version [29.0.0.20230720](https://github.com/square/square-php-sdk/releases/tag/29.0.0.20230720)?

Or even version [26.0.0.20230419](https://github.com/square/square-php-sdk/releases/tag/26.0.0.20230419) to allow for PHP 8.2 to work?

**Comment by NikolaGavric94** [comment]
If you want to you can make a pull request with the changes and I'll check
it in a bit or wait until later today and I'll bump up the version and make
sure there is no breaking changes

**Comment by NikolaGavric94** [comment]
Closing this as it's bee resolved.
