### ISSUE TITLE
One problem with Square Payment

### ISSUE THREAD

**Issue by dreampioneer** [NikolaGavric94/laravel-square#83]
https://js.squareup.com/v2/paymentform
https://js.squareupsandbox.com/v2/paymentform

This urls is returning 404 errors.
What is this?
Please reply to me. I need your help now ASAP.
Thank you.

**Comment by NikolaGavric94** [comment]
I think you got the wrong links for the payment form, not sure what the links are, but I'm pretty sure you can find them on the official documentation, it is required to hook up the form token with this library

**Comment by NikolaGavric94** [comment]
@dreampioneer You are probably looking for this: https://developer.squareup.com/docs/web-payments/take-card-payment

I will close this issue on 3rd of January if there is no response by then. Happy new year!
