### ISSUE TITLE
How to take card payment?

### ISSUE THREAD

**Issue by talha2k** [NikolaGavric94/laravel-square#86]
I am unable to find code example for payment form. where user has to enter card details and then post to the method which performs the charge?

Pleas epoint me in the right direction.

The code available on the official documentation related to the web payments is in Nodejs.

**Comment by NikolaGavric94** [comment]
Hello Talha,

I haven't provided the example code related to the form itself because
people can use different libraries and/or languages to grab the form token.
This gives you, the developer, more flexibility and freedom to implement
that part as you see fit

**Comment by talha2k** [comment]
Thanks for reply Nikola. How can tis be done using laravel?

**Comment by NikolaGavric94** [comment]
This might be a good guide to follow on how to get the form token you need
to send to the backend to formalize the Payment:
https://developer.squareup.com/reference/sdks/web/payments/card-payments

**Comment by talha2k** [comment]
Thank you! Been through that.

I eventually ended up using payment link api! It redirects to square checkout page accepts card input and then redirect back to the redirect url with orderid which can be used to retrieve payment status through an api call.

Thanks anyways! :)

Much appreciated.
